"""
This script will demonstrate how to use Python huggingface_hub package for text generation.
https://huggingface.co/docs/huggingface_hub/v0.20.2/en/package_reference/inference_client#huggingface_hub.InferenceClient.text_generation
https://huggingface.co/docs/huggingface_hub/guides/inference

Get list of models from https://huggingface.co/models
"""

from huggingface_hub import InferenceClient

# Common parameters
API_TOKEN = "PUT_HUGGINGFACE_TOKEN_HERE"

Q1 = "Explain Large Language Models in funny way so that child can understand."
Q2 = "What is cricket provide brief details."

client = InferenceClient(token=API_TOKEN)

# ----------------------------------------------------------------------------------------------------------------------
print(
    client.text_generation(
        model="databricks/dolly-v2-3b", prompt=Q2, max_new_tokens=100
    )
)

"""
Output
------
Cricket is a game played between two teams of eleven players each. The game is played on a rectangular pitch of size 100
yards (100 meters) by 40 yards (30 meters). The game is played with a bat and a ball. The bat has three main parts - a
handle, a barrel and a blade. The ball has two main parts - a leather ball and a coating of rubber on the ball. The game
is played with a number of players from both sides. The players
"""

# ----------------------------------------------------------------------------------------------------------------------
print(
    client.text_generation(
        model="databricks/dolly-v2-3b", prompt=Q1, max_new_tokens=100
    )
)
"""
Output
------
Large Language Models (LLMs) are computer programs that can be trained to generate text that is similar to the text that
was used to train the LLM. LLMs are used in a variety of applications, including question answering, information
retrieval, and summarization. LLMs are trained on large amounts of data, and the training data is often composed of text
generated by humans. LLMs can generate text that is similar to the text that was used to
"""
